### ISSUE TITLE
Unit tests for __repr__

### ISSUE THREAD

**Issue by guoguo12** [guoguo12/billboard-charts#43]
`__repr__` was added in #42. Some tests would be nice!

**Comment by victor-lin** [comment]
The parser makes `ChartEntry.title` and `ChartEntry.artist` unicode strings which yields this output (Python 2):

    billboard.ChartEntry(title=u'Macarena (Bayside Boys Mix)', artist=u'Los Del Rio')

This isn't a problem for Python 3 since all strings are unicode. For testing, this can probably be fixed with `six.text_type()`. Just wondering if we would want to continue using unicode for Python 2. I thought unicode would be used for foreign songs with accented characters in their name (ex. Latin song charts), but it looks like Billboard doesn't keep the unicode characters as of their latest website.

**Comment by victor-lin** [comment]
It doesn't keep unicode characters ([Beyoncé's page](https://www.billboard.com/music/beyonce) shows the accent in the title but not for chart entries).

A small related issue - if they do add unicode characters in the future, the entry correctness test in `test_artist_100.py` might fail since `Beyonce` is used in `2014-07-26-artist-100.txt`. Not sure about the other test text files.
